### PR TITLE
Allow optionally specifying ttl for each cached response

### PR DESCRIPTION
**Pull request by jerodsanto**
I saw this feature in your TODO section and it's something I want for [changelog.com](https://changelog.com) as well, so I took a crack at it. A few notes:

1. I kept this change backwards compatible by adding `cache_response/2`
2. The call to `ConCache.put` uses the correct `%ConCache.Item{}` struct, but I'm not actually testing cache expiry
3. No work on the docs yet, but happy to amend readme and whatever else to make the feature more obvious if/when you approve it

Let me know what you think! 🍻

### CODE REVIEW

**Comment by andreapavoni** [comment]
Hey @jerodsanto thank you for this PR :-)

> I kept this change backwards compatible by adding cache_response/2

That's great! :-)

> The call to ConCache.put uses the correct %ConCache.Item{} struct, but I'm not actually testing cache expiry

Indeed, I don't think we should test cache expiry. I mean, we're just wrapping `ConCache`, the `ttl` feature belongs to that lib. IMHO, of course :-)

> No work on the docs yet, but happy to amend readme and whatever else to make the feature more obvious if/when you approve it

Feel free to add docs and README. This PR is already approved :-)

Again, a big thank you! 🙏

**Comment by jerodsanto** [comment]
Cool, I added a ttl section to the readme. Thanks for approving! Excited to get this merged ✊

**Comment by jerodsanto** [comment]
Hmm hold up I'm testing it in our app and getting an error when passing `:infinity` as the ttl (even though ConCache docs say you can do this). Will update here soon...

**Comment by jerodsanto** [comment]
ok I was reading the wrong docs (0.13.0 vs 0.12.1) 🤦‍♂️ 

Passing `:infinity` as a ttl is not supported until ConCache 0.13. It seems like that version has some nice improvements over 0.12, so we should consider upgrading to it soon. But for now, I'll remove that example from the readme and we can call this feature done.

**Comment by andreapavoni** [comment]
Great work! Let's upgrade to ConCache 0.13 :-)

**Comment by jerodsanto** [comment]
Okie doke! Do you want a separate PR or roll it in to this one?

**Comment by andreapavoni** [comment]
This one is ok, after all it all started with this PR :-P

**Comment by jerodsanto** [comment]
Done! However, build failed on Elixir 1.4...

> the dependency :con_cache requires Elixir "~> 1.5" but you are running on v1.4.5

Sooo we need to decide if we want to revert to ConCache 0.12 or remove support for Elixir 1.4 (I prefer the latter, because progress).

**Comment by andreapavoni** [comment]
I've removed support for Elixir 1.4 in `master` ✌️

Thank you for this PR!

**Comment by jerodsanto** [comment]
Yay! 🥂

Is this a big enough improvement to cut a release?

**Comment by andreapavoni** [comment]
@jerodsanto of course! https://hex.pm/packages/plug_ets_cache/0.3.0 🕺

**Comment by jerodsanto** [comment]
💚💚💚

**Pull request merged**
